[app]
name = "postgres_example"
version = "0.0.4"
debug = true

[server]
host = "localhost"
port = 8080

[plugins.sql]
host = "localhost"
port = 5432
user = "postgres"
password = "postgres"
db = "postgres"
