[app]
name = "Advanced Plugins Demo"
version = "1.0.0"
debug = true

[server]
host = "localhost"
port = 8080

[plugins.sql]
host = "localhost"
port = 5432
user = "postgres"
password = "password"
db = "gorgo_demo"
max_conns = 25
min_conns = 5

[plugins.redis]
host = "localhost"
port = 6379
password = ""
db = 0
pool_size = 10

[plugins.monitoring]
enabled = true
report_interval = 30
log_requests = true 